version: '2'

services:
  discovery-store:
    image: mariadb:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - discovery_data
  discovery-agent:
    depends_on:
      - "discovery-store"
    image: cloudiator/discovery-agent:latest
    environment:
      - JPA_USER=${MYSQL_USER}
      - JPA_PASSWORD=${MYSQL_PASSWORD}
      - JPA_DATABASE=${MYSQL_DATABASE}
      - KAFKA_BOOTSTRAP_SERVERS
      - JPA_HOST=mariadb
